# Generated by Django 2.2.3 on 2019-07-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_back',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_front',
            new_name='front',
        ),
    ]
